routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;


    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::resource('stores', 'StoreController');
    Route::get('/get-stores/data', 'StoreController@dataTable')->name('stores.dataTable');
    Route::get('/get-nearest-stores', 'StoreController@getNearestStores')->name('stores.getNearestStores');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/stores/near-me', [App\Http\Controllers\Dashboard\StoreController::class, 'getNearestStores'])->name('getNearestStores');

app/Models/Store.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'address',
        'latitude',
        'longitude',
    ];

    public static function laratablesCustomActions($store)
    {
        return view('dashboard.store.custom._actions', compact('store'))->render();
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('dashboard.dashboard');
    }
}

app/Http/Controllers/Dashboard/StoreController.php
<?php
namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Store;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Builder;
class StoreController extends Controller
{
    public function index()
    {
        return view('dashboard.store.index');
    }

    public function dataTable()
    {
        $stores = Store::all()->toArray();
        $data = [
            "draw" => 1,
            "recordsTotal" => count($stores),
            "recordsFiltered" => count($stores),
            "data" => $stores
        ];
        return json_encode($data);
    }

    public function create()
    {
        return view('dashboard.store.create');
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $address = str_replace(' ', '+', $data['address']);

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://maps.googleapis.com/maps/api/geocode/json?address='. $address .'&key=AIzaSyC1dNlmvqZYGI7cWZangz-nNm1kFApDrgQ');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 0);

        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Content-Type: text/plain';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = json_decode(curl_exec($ch));
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        if ($result) {
            $latitude = $result->results[0]->geometry->location->lat;
            $longitude = $result->results[0]->geometry->location->lng;
            $data['latitude'] = $latitude;
            $data['longitude'] = $longitude;
        }

        $store = Store::create($data);


        flash()->success('Store Created Successfully!');
        return redirect()->route('stores.index');
    }

    public function show($id)
    {
        $store = Store::findOrFail($id);
        return view('dashboard.store.show', compact('store'));
    }


    public function edit($id)
    {
        $store = Store::findOrFail($id);
        return view('dashboard.store.edit', compact('store'));
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();
        $store = Store::find($id);
        if ($store->address != $data['address']) {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, 'https://maps.googleapis.com/maps/api/geocode/json?address=18+Mazmanyan+street,+Yerevan,+Armenia&key=AIzaSyC1dNlmvqZYGI7cWZangz-nNm1kFApDrgQ');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 0);

            $headers = array();
            $headers[] = 'Accept: application/json';
            $headers[] = 'Content-Type: text/plain';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

            $result = json_decode(curl_exec($ch));
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);

            if ($result) {
                $latitude = $result[0]['geometry']['location']['lat'];
                $longitude = $result[0]['geometry']['location']['lng'];
                $data['latitude'] = $latitude;
                $data['longitude'] = $longitude;
            }
        }
        $store->update($data);

        flash()->success('Updated Successfully!');
        return redirect()->route('stores.index');

    }

    public function destroy($id)
    {
        $store = Store::whereId($id)->first();
        if (!$store) {
            abort(404);
        }

        $store->delete();
        flash()->success('Store deleted!');
        return redirect()->route('stores.index');
    }

    public function getNearestStores(Request $request)
    {
        $latitude = $request->get('latitude');
        $longitude = $request->get('longitude');

        $stores =  Store::select(DB::raw("name,description,address,latitude,longitude, ( 6371 * acos( cos( radians('$latitude') ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians('$longitude') ) + sin( radians('$latitude') ) * sin( radians( latitude ) ) ) ) AS distance"))->havingRaw('distance < 50')->orderBy('distance')
            ->get()->toArray();

        return json_encode($stores);
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/dashboard/components/form/__examples.blade.php
@include('dashboard.components.form._text', (['name' => 'name']))
@include('dashboard.components.form._number', (['name' => 'count']))
@include('dashboard.components.form._textarea', (['name' => 'content', 'editor' => true, 'rows' => 5]))
@include('dashboard.components.form._select', (['name' => 'type', 'data' => ['active', 'inactive'], 'selected' => 0, 'select_2' => true, 'multiple' => false]))
@include('dashboard.components.form._radio', (['name' => 'is_checked', 'text' => ['Yes', 'No'], 'values' => [1, 0], 'selected' => 1]))
@include('dashboard.components.form._checkbox', (['name' => 'status', 'checked' => true, 'value' => 'active', 'text' => ['Inactive', 'Active']]))

resources/views/dashboard/components/form/_checkbox.blade.php
{!! Form::label($name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
<div class="d-flex align-items-center">
    <label>{{$text[0]}}</label>
    <span class="kt-switch kt-switch--icon mr-3 ml-3">
        <label>
            {!! Form::checkbox($name, $value ?? 1, $checked ?? false, ['class' => 'form-input-styled']); !!}
            <span></span>
        </label>
    </span>
    <label>{{$text[1]}}</label>
</div>
{!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}

resources/views/dashboard/components/form/_date.blade.php
{!! Form::label($name, __(ucfirst(str_replace('_', ' ', $name)))) !!}
<input type="date" name="{{$name}}" id="{{$name}}" required class="form-control"  placeholder="{{__(ucfirst(str_replace('_', ' ', $name)))}}" value="{{(old($name)) ? old($name) : (isset($object) && $object ? \Carbon\Carbon::parse($object)->format('Y-m-d') : null)}}">
{!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}

resources/views/dashboard/components/form/_email.blade.php
{!! Form::label($label ?? $name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
{!! Form::email($name, $value ?? null, ['id' => $name, 'class' => 'form-control', 'placeholder' => __(ucfirst(str_replace('_', ' ', $label ?? $name)))]) !!}
{!! isset($errors) ? $errors->first($name, '<span class="form-text text-danger">:message</span>') : '' !!}

resources/views/dashboard/components/form/_file.blade.php
<div class="input-group" id="fileDiv">
    <span class="input-group-btn">
    <a id="{{$name}}_lfm" data-input="{{$name}}_thumbnail" data-preview="{{$name}}_holder" class="btn btn-primary text-white fileLink">
        <i class="flaticon2-photo-camera" style="color: #fff"></i> Выберите файл</a>
    </span>
    <input id="{{$name}}_thumbnail" class="form-control fileText" type="text" readonly value="{{ ($value && is_array($value) || is_object($value)) ? collect($value)->first() : $value }}">
    <input type="file" name="{{$name}}@isset($array)[]@endisset" id="{{$name}}_lfm_hid" class="form-control fileHidden"
           accept="" style="display: none" @isset($multiple) {{'multiple'}} @endisset>
</div>

{!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}
{!! $errors->first($name . '.*', '<span class="form-text text-danger">:message</span>') !!}


{{--@isset($value)--}}
{{--    @if(is_array($value) || is_object($value))--}}
{{--        <br/>--}}
{{--        @foreach ($value as $val)--}}
{{--            <img src="{{$val}}" width="100" height="100" alt="file">--}}
{{--        @endforeach--}}
{{--    @else--}}
{{--        <img src="{{$value}}" width="200" alt="file">--}}
{{--    @endif--}}
{{--@endisset--}}

@section('scripts')
    <script>
        $('#fileDiv a').each(function(elem, obj) {
            $('#' + obj.id).on('click', function() {
            $('#' + obj.id + '_hid').click();
          });
        })


        $('input[type="file"]').each(function(elem, obj) {
          $('#' + obj.id).on('change', function() {
            var value =$('#' + obj.id).val();
            var name = obj.name;
            var name = ( name.includes('[') && name.includes(']') ) ? obj.name.replace('[]','') : obj.name;
            $('#' + name + '_thumbnail').val(value);
          });
        })

    </script>
@endsection

resources/views/dashboard/components/form/_number.blade.php
    {!! Form::label($label ?? $name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
    {!! Form::number($name, null, ['id' => $id ?? '', 'class' => 'form-control', 'placeholder' => __(ucfirst(str_replace('_', ' ', $placeholder ?? '')))]) !!}
    {!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}

resources/views/dashboard/components/form/_password.blade.php
{!! Form::label($label ?? $name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
{!! Form::password($name, null, ['id' => $name, 'class' => 'form-control', 'placeholder' => __(ucfirst(str_replace('_', ' ', $label ?? $name)))]) !!}
{!! isset($errors) ? $errors->first($name, '<span class="form-text text-danger">:message</span>') : '' !!}

<script>
    $('#password').addClass('form-control');
    $('#password').attr('placeholder', '{{ ucfirst(str_replace('_', ' ', $label ?? $name)) }}');
</script>

resources/views/dashboard/components/form/_radio.blade.php
{!! Form::label($name, __(ucfirst(str_replace('_', ' ', $name)))) !!}
    <div class="kt-radio-inline">
        <label class="kt-radio kt-radio--solid">
            {!! Form::radio($name, $values[1] ?? 1, $selected ?? true, ['class' => 'form-input-styled', 'data-fouc' => true]); !!}
            {{$text[0]}}
            <span></span>
        </label>

        <label class="kt-radio kt-radio--solid">
            {!! Form::radio($name, $values[1] ?? 0, $selected ?? false, ['class' => 'form-input-styled', 'data-fouc' => true]); !!}
            {{$text[1]}}
            <span></span>
        </label>
    </div>
{!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}

resources/views/dashboard/components/form/_select.blade.php
{!! Form::label($name, $display_name ?? __(ucfirst(str_replace('_', ' ', str_replace('_id', '', $name))))) !!}
{!! Form::select($name . ((isset($multiple) && $multiple) ? '[]' : ''), $data, $selected ?? null, ['id' => $id??'', 'class' => 'form-control', 'multiple' => $multiple ?? false]) !!}
{!! $errors->first($name, '<span class="form-text text-danger">:message</span>') !!}

@if(isset($select_2) && $select_2)
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <script>

    var select_2_tags = false;
    @if(isset($tags) && $tags)
        select_2_tags = true;
    @endif
    $('#{{$id??''}}').select2({
        tags: select_2_tags
    });
</script>
@endif

resources/views/dashboard/components/form/_slug.blade.php
{!! Form::label($name, __('dashboard.Friendly URL')) !!}
<div class="input-group">
    <span class="slugSpan">{{$text}}</span>
    <input class="form-control" type="text" name="{{$name}}" value="{{$value}}">
    <span class="slugSpan">/</span>
</div>
@section('css')
    <style>
        .slugSpan {
            background: lightgray;
            color: white;
            padding: 10px;
            border-radius: 3px;
        }
    </style>
@endsection

resources/views/dashboard/components/form/_text.blade.php
{!! Form::label($label ?? $name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
{!! Form::text($name, $value ?? null, ['id' => $name, 'class' => 'form-control', 'placeholder' => __(ucfirst(str_replace('_', ' ', $placeholder ?? '')))]) !!}
{!! isset($errors) ? $errors->first($name, '<span class="form-text text-danger">:message</span>') : '' !!}

resources/views/dashboard/components/form/_textarea.blade.php
{!! Form::label($name, __(ucfirst(str_replace('_', ' ', $label ?? $name)))) !!}
{!! Form::textarea($name, $value ?? null, ['id' => $name, 'class' => 'form-control', 'rows' => $rows ?? 5, 'placeholder' => __(ucfirst(str_replace('_', ' ', $label ?? $name)))]) !!}
{!! isset($errors) ? $errors->first($name, '<span class="form-text text-danger">:message</span>') : '' !!}

@if(isset($editor) && $editor == true)
    <script>

        CKEDITOR.replace('{{$name}}',
            {

            }
        );

    </script>
@endif

resources/views/dashboard/store/create.blade.php
@extends('dashboard.layouts.app')
@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid align-items-center">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Stores</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <div class="kt-subheader__breadcrumbs">
                        <a href="{{route('dashboard')}}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.index')}}" class="kt-subheader__breadcrumbs-link">
                            Stores</a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.create')}}" class="kt-subheader__breadcrumbs-link">
                            Create Store</a>
                    </div>
                </div>
                <div class="">
                    <a href="" class="btn btn-secondary j_return_back">Cancel</a>
                    <button type="submit" class="btn btn-primary" id="object-form-confirm">Save</button>
                </div>
            </div>
        </div>

        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="kt-portlet">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Create new store
                                </h3>
                            </div>
                        </div>
                        <form action="{{route('stores.store')}}" method="post" id="object-form" class="kt-form kt-form--label-right" enctype="multipart/form-data">
                            @csrf
                            @method('POST')
                            @include('dashboard.store.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/dashboard/store/custom/_actions.blade.php
<span style="overflow: visible; position: relative; width: 110px;white-space: nowrap">
     <a href="{{route('stores.show', $store->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Show Details">
            <i class="flaticon-eye"></i>
     </a>
    <a href="{{route('stores.edit', $store->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit details">
          <i class="flaticon-edit"></i>
    </a>
    <form action="{{route('stores.destroy', $store->id)}}" method="POST" style="display: none" onsubmit="return confirm('Are you sure?')">
        @csrf
        @method('DELETE')
    </form>
    <a href="#" onclick="$(this).prev().submit()" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Delete">
         <i class="flaticon2-trash"></i>
    </a>
</span>

resources/views/dashboard/store/edit.blade.php
@extends('dashboard.layouts.app')
@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid align-items-center">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Stores</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <div class="kt-subheader__breadcrumbs">
                        <a href="{{route('dashboard')}}" class="kt-subheader__breadcrumbs-home"><i
                                    class="flaticon2-shelter"></i></a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.index')}}" class="kt-subheader__breadcrumbs-link">
                            Stores</a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.edit', $store->id)}}"
                           class="kt-subheader__breadcrumbs-link">
                            Edit Store - {{$store->id}} </a>
                    </div>
                </div>
                <div class="">
                    <a href="" class="btn btn-secondary j_return_back">Cancel</a>
                    <button type="submit" class="btn btn-primary" id="object-form-confirm">Update</button>
                </div>
            </div>
        </div>

        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="kt-portlet">
                        <div class="kt-portlet__head">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Edit Store - {{$store->id}}
                                </h3>
                            </div>
                        </div>
                        {!! Form::model($store, [
                         'method' => 'PATCH',
                         'files' => true,
                         'id' => 'object-form',
                         'class' => 'kt-form kt-form--label-right',
                         'url' => route('stores.update',$store->id),
                       ]) !!}

                        @csrf
                        @include('dashboard.store.form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/dashboard/store/index.blade.php
@extends('dashboard.layouts.app')

@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid align-items-center">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Stores</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <div class="kt-subheader__breadcrumbs">
                        <a href="{{route('dashboard')}}" class="kt-subheader__breadcrumbs-home"><i
                                class="flaticon2-shelter"></i></a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.index')}}" class="kt-subheader__breadcrumbs-link">
                            Stores </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="kt-portlet kt-portlet--mobile">
                        <div class="kt-portlet__head kt-portlet__head--lg">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Stores
                                </h3>
                            </div>
                            <div class="kt-portlet__head-toolbar">
                                <div class="kt-portlet__head-wrapper">
                                    <div class="kt-portlet__head-actions">
                                        <a href="{{route('stores.create')}}" class="btn btn-brand btn-elevate btn-icon-sm">
                                            <i class="flaticon2-plus"></i>
                                            Create Store
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @include('flash::message')
                        <div class="kt-portlet__body">
                            <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded">
                                <table class="table-responsive-lg kt-datatable__table dataTable">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>Address</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $('.dataTable').DataTable({
            serverSide: true,
            processing: true,
            responsive: true,
            ajax: "{{route('stores.dataTable')}}",
            columns: [
                {data: 'id'},
                {data: 'name'},
                {data: 'description'},
                {data: 'address'},
                {
                    data: null,
                    render: function(data, type, row) {
                        return '<span style="overflow: visible; position: relative; width: 110px;white-space: nowrap">' +
                            '<a href="/dashboard/stores/' + row.id + '" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Show Details"><i class="flaticon-eye"></i></a>' +
                            '<a href="/dashboard/stores/' + row.id + '/edit" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit details"><i class="flaticon-edit"></i></a>' +
                            '<form action="/dashboard/stores/' + row.id + '" method="POST" style="display: none" onsubmit="return confirm(`Are you sure?`)">' +
                            '@csrf'+
                            '@method("DELETE")'+
                            '</form>' +
                            '<a href="#" onclick="$(this).prev().submit()" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Delete"> <i class="flaticon2-trash"></i> </a> </span>';
                    },
                    orderable: false,
                    searchable: false
                }
            ],
        });
    </script>
@endsection

resources/views/dashboard/store/show.blade.php
@extends('dashboard.layouts.app')
@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">

        <div class="kt-subheader  kt-grid__item" id="kt_subheader">
            <div class="kt-container  kt-container--fluid align-items-center">
                <div class="kt-subheader__main">
                    <h3 class="kt-subheader__title">Stores</h3>
                    <span class="kt-subheader__separator kt-subheader__separator--v"></span>
                    <div class="kt-subheader__breadcrumbs">
                        <a href="{{route('dashboard')}}" class="kt-subheader__breadcrumbs-home"><i
                                    class="flaticon2-shelter"></i></a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.index')}}" class="kt-subheader__breadcrumbs-link">
                            Stores  </a>
                        <span class="kt-subheader__breadcrumbs-separator"></span>
                        <a href="{{route('stores.show', $store->id)}}" class="kt-subheader__breadcrumbs-link">
                            Store - {{$store->id}} </a>
                    </div>
                </div>

                <form action="{{route('stores.destroy', $store->id)}}" method="post"
                      onsubmit="return confirm('Are you sure?')" class="mr-1">
                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <button type="submit" class="btn btn-danger btn-icon" title="Delete"><i class="flaticon2-trash"></i>
                    </button>
                </form>
            </div>
        </div>

        <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="kt-portlet kt-portlet--mobile">
                        <div class="kt-portlet__head kt-portlet__head--lg">
                            <div class="kt-portlet__head-label">
                                <h3 class="kt-portlet__head-title">
                                    Store - {{$store->id}}
                                </h3>
                            </div>
                        </div>

                        <div class="kt-portlet__body">
                            <table class="table card-table table-responsive-lg">
                                <tbody>
                                    <tr>
                                        <th>Name</th>
                                        <td><span class="text-muted">{{$store->name}}</span></td>
                                    </tr>

                                    <tr>
                                        <th>Address</th>
                                        <td><span class="text-muted">{{$store->address}}</span></td>
                                    </tr>

                                    <tr>
                                        <th>Description</th>
                                        <td><span class="text-muted">{{$store->description}}</span></td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                        <div class="card-footer text-right">
                            <div class="d-flex">
                                <a href="#" class="btn btn-link j_return_back">Back</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection